
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "psauygzfbxvefnetudem"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, the user will instead get an error if they weren't invited.
# It changes nothing about sign up, but gives a tighter error message, particularly for use in self-hosted scenarios where auto signups aren't desired.
# Ignored when `enable_signup` is disabled.
# Disables signup using email and password. Also disables user account recovery via email (i.e. password reset).
# In case of programmatic errors that involve email and passwords, it silently fails. This prevents unwanted information disclosure.
# In some cases where enable_signup is disabled, this property will still protect a user if the API was directly called, i.e. a platform UI doesn't provide a entry point for user signups, but
# a bad actor is manipulating the browser's JS test console.
# Can be useful when a user has another way of creating an account like SSO with `external` provider.
# Role for the created account
default_role = "authenticated"

[functions.award-xp]
verify_jwt = true

[functions.add-calendar-event]
verify_jwt = true

[functions.generate-waiting-message]
verify_jwt = false

[functions.refresh-topics]
verify_jwt = true

[functions.sync-creator-settings]
verify_jwt = true

[functions.get-content-idea-details]
verify_jwt = false
