
project_id = "psauygzfbxvefnetudem"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[inbucket]
enabled = true

[functions]
[functions.create-assistant-thread]
verify_jwt = true
[functions.send-assistant-message]
verify_jwt = true
[functions.get-assistant-messages]
verify_jwt = true
