
psauygzfbxvefnetudem = "psauygzfbxvefnetudem"

[functions.generate-strategy-chat]
verify_jwt = true

[functions.refresh-topics]
verify_jwt = true

[functions.sync-creator-settings]
verify_jwt = true

